/*******************************************************************************
 * Copyright (c) 2009 Composent, Inc. and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *    Composent, Inc. - initial API and implementation
 ******************************************************************************/
package org.eclipse.equinox.internal.examples.http.webapp.hello;

import javax.servlet.ServletContext;

public class HelloPage {

	// This alias is mapped to a path inside our bundle via the markup in
	// web.xml
	// See <osgi-resource> elements in /META-INF/web.xml
	private static final String RESOURCEALIAS = "resources/";
	// Some resources to use for the page
	private static final String LOGO_IMAGE = RESOURCEALIAS
			+ "EclipseRT_Logo_Small.jpg";
	private static final String SRC_ZIP = RESOURCEALIAS
			+ "org.eclipse.equinox.examples.http.webapp.hello_1.0.0.zip";
	private static final String SECOND_PAGE = RESOURCEALIAS + "second.html";

	public static String getHtmlAsString(ServletContext servletContext) {
		StringBuffer sb = new StringBuffer(
				"<html><body><p><a href=\"http://www.eclipse.org/rt/\"><img src=\"");
		sb.append(getHref(servletContext, LOGO_IMAGE)).append(
				"\"/></a></p><p></p>");
		sb
				.append(
						"<br>Your <b><a href=\"http://www.eclipse.org/rt/\">EclipseRT</a></b> web server says: <h1>Hello World!</h1>")
				.append("<hr>");
		sb
				.append("<p>This page was generated by a simple servlet that uses the OSGi HttpService.</p>");
		sb
				.append("<p>For more info about <a href=\"http://www.eclipse.org/rt/\">EclipseRT</a> project see the following links</p>");
		sb
				.append("<ul><li><a href=\"http://www.eclipse.org/rt/\">http://www.eclipse.org/rt</a></li>");
		sb
				.append("<li><a href=\"http://www.eclipse.org/equinox\">http://www.eclipse.org/equinox</a></li>");
		sb.append("</ul>");
		sb
				.append("<p>Source code for this <a href=\"http://www.eclipse.org/rt/\">EclipseRT</a> webapp can be found in "
						+ getLinkMarkup(servletContext, SRC_ZIP, "this zip")
						+ ".  Once downloaded, the zip can be imported into an Eclipse workspace by choosing <b>File->Import...->Existing Projects Into Workspace->Next->Select archive file</b> within Eclipse.</p>");
		sb.append("</body></html>");
		sb.append("<p>Click ").append(
				getLinkMarkup(servletContext, SECOND_PAGE, "here")).append(
				" to navigate to another test page</p>");
		return sb.toString();
	}

	private static String getLinkMarkup(ServletContext servletContext,
			String resource, String text) {
		// return markup
		return "<a href=\"" + getHref(servletContext, resource) + "\">" + text
				+ "</a>";
	}

	private static String getHref(ServletContext servletContext, String resource) {
		// Get context path (e.g. our servlet name)
		String contextPath = servletContext.getContextPath();
		// If it doesn't already end with /, then tack it on.
		if (!contextPath.endsWith("/"))
			contextPath = contextPath + "/";
		// If the resource starts with /, then remove it (it's already on
		// contextPath)
		if (resource.startsWith("/"))
			resource = resource.substring(1);
		return contextPath + resource;
	}

}
